name: Auto Deploy Lab

on:
  push:
    branches:
      - main

jobs:
  deploy-ke-server:
    runs-on: self-hosted

    steps:
      - name: 1. Menarik Kode Terbaru
        uses: actions/checkout@v4

      - name: 2. Eksekusi Skrip Deployment
        run: |
          docker compose down
          docker compose up -d
